### ISSUE TITLE
remove swfuploader.swf due to the End-of-Life of adobe flash player

### ISSUE THREAD

**Issue by ryang-a** [jiakuan/gwt-uploader#9]
Since Adobe flash player gets terminated(https://www.adobe.com/products/flashplayer/enterprise-end-of-life.html), it's probably necessary to remove any .swf files or related code to it.

**Comment by jiakuan** [comment]
That's a good idea.
Pull requests are welcomed.

**Comment by Lonzak** [comment]
We just stumbled over the same issue - this would be highly appreciated!

**Comment by Lonzak** [comment]
I create a pull request (which needs a code review) however might be a first step...
https://github.com/jiakuan/gwt-uploader/pull/10

**Comment by jiakuan** [comment]
I will have a look over the weekend.
It's also a good time to upgrade GWT to `2.10.0`

**Comment by Lonzak** [comment]
> I will have a look over the weekend. It's also a good time to upgrade GWT to `2.10.0`

I thought so too but didn't want to mix those two things...

**Comment by jiakuan** [comment]
@Lonzak I've upgraded GWT to 2.10.0, and also upgraded gwt gradle plugin to the latest. Fixed warnings etc.

A new release has been created and pushed to Maven Central:

```
implementation 'org.docstr:gwt-uploader:1.2.4'
```

As I don't own the previous domain any more, so I renamed the group name as well.

**Comment by jiakuan** [comment]
It may need a few hours to be shown in Maven Central

**Comment by Lonzak** [comment]
Appreciated - thank you!

**Comment by Lonzak** [comment]
I tried it out in our project however I got problems with the maven transitive dependencies.
Even though the scope is set to runtime it breaks my GWT build since it is part of our EAR/WAR file. The culprit was:

```
<groupId>com.google.jsinterop</groupId>
<artifactId>base</artifactId>
<version>1.0.0</version>
```

1. I can't see any usage of the package `jsinterop.base` so can it be removed? 
2. Also `elemental2` is only used in the demo and not the uploader itself.  Maye we should think about two different poms (and a parent.pom)?
3. Also I didn't find a direct usage of `javax.annotation` nonnull / nullable etc. So the reference to jsr305 can also be removed?
4. Jackson also seems not to be used - remove?

**Update**: I now excluded all transitive dependencies and it is (still) working. However since we have a GWT project `gwt-user` and `guava` did already exists.

**Comment by jiakuan** [comment]
As a test, can you please try excluding the problematic dependencies in your POM files?

I will check and remove/exclude the unnecessary dependencies from the library.

----

Just saw your update - I will then check the library dependencies.

**Comment by jiakuan** [comment]
Have moved `com.google.jsinterop:base` and `elemental2` into demo project, now the core lib only depends on `gwt-user`.

`javax.annotation` and JSON related dependencies have also been removed from the demo project.

A new version `org.docstr:gwt-uploader:1.2.5` has been released to Maven Central.

**Comment by Lonzak** [comment]
I think you forgot to tag that version: https://github.com/jiakuan/gwt-uploader/tags

**Comment by jiakuan** [comment]
> I think you forgot to tag that version: https://github.com/jiakuan/gwt-uploader/tags

Created a tag for 1.2.5
